"use client";

import { FormEvent, useEffect, useState } from "react";
import { coreStyles as styles } from "../../components/crm/CoreShell";

type Role = { id: string; code: string; name: string; description: string };
type Member = { id: string; name: string; email: string; storeId: string; status: string; roleName: string };
const labels: Record<string, string> = { invited: "Convite pendente", active: "Ativo", suspended: "Suspenso", inactive: "Inativo" };

export default function SettingsConsole() {
  const [users, setUsers] = useState<Member[]>([]), [roles, setRoles] = useState<Role[]>([]), [message, setMessage] = useState("Carregando controles de acesso…"), [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const response = await fetch("/api/configuracoes/usuarios", { cache: "no-store" }); const data = await response.json(); if (!response.ok) setMessage(data.error ?? "Não foi possível carregar os acessos."); else { setUsers(data.users); setRoles(data.roles); setMessage(""); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const invite = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const response = await fetch("/api/configuracoes/usuarios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const data = await response.json(); setMessage(data.message ?? data.error ?? "Convite criado."); if (response.ok) { event.currentTarget.reset(); await load(); } };
  const changeStatus = async (id: string, status: string) => { const response = await fetch("/api/configuracoes/usuarios", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await response.json(); setMessage(data.error ?? "Acesso atualizado."); if (response.ok) await load(); };
  return <div className={styles.grid2}><section className={styles.card}><h2>Usuários e acessos</h2><p>Convide pessoas, defina seu perfil e controle o status do acesso ao CRM.</p>{message ? <div className={styles.warning}>{message}</div> : null}{loading ? null : users.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Usuário</th><th>Perfil</th><th>Loja</th><th>Status</th><th>Ação</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><br /><small>{user.email}</small></td><td>{user.roleName}</td><td>{user.storeId || "Todas as lojas"}</td><td><span className={styles.badge}>{labels[user.status] ?? user.status}</span></td><td>{user.status === "active" ? <button className={styles.action} onClick={() => void changeStatus(user.id, "suspended")}>Suspender</button> : <button className={styles.action} onClick={() => void changeStatus(user.id, "active")}>Ativar</button>}</td></tr>)}</tbody></table></div> : <div className={styles.empty}>Nenhum usuário adicional cadastrado.</div>}</section><aside className={styles.card}><h2>Convidar usuário</h2><form className={styles.settingsForm} onSubmit={invite}><label>Nome<input name="name" required /></label><label>E-mail corporativo<input name="email" type="email" required /></label><label>Telefone<input name="phone" /></label><label>Loja ou unidade<input name="storeId" placeholder="Ex.: São Bernardo" /></label><label>Perfil<select name="roleId" required defaultValue=""><option value="" disabled>Selecionar perfil</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button className={styles.primary} type="submit" disabled={loading || !roles.length}>Criar convite</button></form><h2 className={styles.sectionTitle}>Segurança</h2><p className={styles.muted}>Senhas serão definidas e recuperadas pelo provedor de autenticação. O CRM não armazena senhas.</p><h2 className={styles.sectionTitle}>Auditoria</h2><p className={styles.muted}>Convites, suspensões e mudanças de acesso ficam registrados com data e responsável.</p></aside></div>;
}
