import { requireChatGPTUser } from "../chatgpt-auth";
import { ensureMatchTables } from "../../lib/match-engine";

type Row = { id: string; vehicle_label: string; vehicle_price: number; score: number; reasons: string; message_draft: string; status: string; source_type: string; created_at: string; name: string; whatsapp: string; email: string; city: string; alerts_consent: number };
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
export default async function MatchesPage() {
  await requireChatGPTUser("/matches"); const { env } = await import("cloudflare:workers"); await ensureMatchTables(env.DB);
  const result = await env.DB.prepare(`SELECT vm.*, bp.name, bp.whatsapp, bp.email, bp.city, bp.alerts_consent FROM vehicle_matches vm JOIN buyer_profiles bp ON bp.id = vm.buyer_profile_id ORDER BY vm.score DESC, vm.created_at DESC LIMIT 200`).all<Row>();
  const rows = result.results ?? [];
  return <main className="crm-page"><header className="crm-header"><a className="brand" href="/"><span>AutoPonte</span> Veículos</a><div><strong>AutoPonte Match</strong><a href="/crm">CRM integrado</a><a href="/oportunidades">Avaliações</a><a href="/">Voltar ao site</a></div></header>
    <section className="crm-summary"><div><span>Correspondências</span><strong>{rows.length}</strong></div><div><span>Aguardando revisão</span><strong>{rows.filter((row) => row.status === "review_pending").length}</strong></div><div><span>Compatibilidade alta</span><strong>{rows.filter((row) => row.score >= 80).length}</strong></div></section>
    <section className="crm-content"><div className="crm-title"><div><p className="eyebrow dark">Ponte entre compra e venda</p><h1>Oportunidades encontradas automaticamente</h1></div><p>Revise compatibilidade, disponibilidade e consentimento antes de abrir o contato. O sistema prepara a mensagem, mas não a envia sozinho.</p></div>
      {rows.length === 0 ? <div className="crm-empty">Nenhuma correspondência ainda. Novos perfis de compra e veículos recebidos alimentarão esta fila.</div> : <div className="match-queue">{rows.map((row) => { const reasons = JSON.parse(row.reasons || "[]") as string[]; const phone = row.whatsapp.replace(/\D/g, ""); const wa = `https://wa.me/55${phone}?text=${encodeURIComponent(row.message_draft)}`; return <article className="match-card" key={row.id}><div className="match-card-score"><strong>{row.score}%</strong><span>compatível</span></div><div className="match-card-body"><div className="opportunity-tags"><span>{row.source_type === "trade_in" ? "Possível troca" : "Pré-consignação"}</span><span className={row.status === "review_pending" ? "lead-warm" : "lead-review"}>{row.status === "review_pending" ? "Revisar contato" : "Uso interno"}</span></div><h2>{row.vehicle_label}</h2><p>{brl.format(row.vehicle_price)} • potencial comprador em {row.city}</p><h3>{row.name}</h3><p>{row.whatsapp} • {row.email}</p><ul>{reasons.map((reason) => <li key={reason}>✓ {reason}</li>)}</ul><blockquote>{row.message_draft}</blockquote>{row.status === "review_pending" ? <a className="review-contact" href={wa} target="_blank" rel="noreferrer">Revisar e abrir WhatsApp</a> : <p className="no-consent">Sem autorização para alertas: use apenas como inteligência comercial interna.</p>}</div></article>; })}</div>}
    </section></main>;
}
