import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { buildCasesMissionControl, RECENTLY_LOST_DAYS, type MissionControlCaseSource, type MissionControlTaskSource } from "../lib/commercial-cases/mission-control.ts";

const now=new Date("2026-08-31T12:00:00");
const base=(id:string,status="active",closedAt:Date|null=null):MissionControlCaseSource=>({id,pilotCode:id,customerName:`Cliente ${id}`,status,finalOutcome:status==="lost"?"negotiation_lost":"",noNextActionReason:"Aguardando definição",updatedAt:now,closedAt,sellerName:"Vendedor"});
const task=(caseId:string,priority:string,dueAt:string):MissionControlTaskSource=>({id:`task-${caseId}-${priority}`,caseId,actionType:"CONTACT_CUSTOMER",ownerId:"owner",ownerName:"Responsável",dueAt:new Date(dueAt),priority,status:"OPEN",context:"",createdAt:now});

test("orders canonical Case states by the Mission Control sequence",()=>{const cases=[base("remaining"),base("none"),base("high"),base("today"),base("late"),base("urgent"),base("lost","lost",new Date("2026-08-30T10:00:00"))];const tasks=[task("remaining","NORMAL","2026-09-02T10:00:00"),task("high","HIGH","2026-09-03T10:00:00"),task("today","NORMAL","2026-08-31T16:00:00"),task("late","NORMAL","2026-08-30T10:00:00"),task("urgent","URGENT","2026-09-05T10:00:00")];const model=buildCasesMissionControl(cases,tasks,[{caseId:"lost",lossReason:"PRICE"}],now);assert.deepEqual(model.items.map(item=>item.id),["urgent","late","today","high","none","lost","remaining"]);assert.deepEqual(model.counters,{overdue:1,dueToday:1,noNextAction:1,highOrUrgent:2,recentlyLost:1});assert.equal(model.items.find(item=>item.id==="lost")?.reason,"Preço");});
test("uses canonical Next Action derivation and excludes old or closed cases",()=>{const cases=[base("case"),base("old-lost","lost",new Date("2026-08-01")),base("closed","closed",new Date("2026-08-30"))];const tasks=[task("case","NORMAL","2026-08-30T10:00:00"),task("case","URGENT","2026-09-05T10:00:00")];const model=buildCasesMissionControl(cases,tasks,[],now);assert.equal(model.items.length,1);assert.equal(model.items[0]?.priority,"URGENT");assert.equal(model.items[0]?.state,"URGENT");});
test("keeps Slice 2 reads authenticated, writes permissioned, and schema failure safe",()=>{const page=readFileSync("app/crm/page.tsx","utf8"),route=readFileSync("app/api/cases/[id]/route.ts","utf8"),model=readFileSync("lib/commercial-cases/mission-control.ts","utf8");assert.match(page,/requireChatGPTUser\("\/crm"\)/);assert.match(page,/try\{model=await getCasesMissionControl\(\);\}catch/);assert.match(page,/<CasesMissionControl model=\{model\}/);assert.match(route,/requirePermission\(actor,"seller_operations\.manage"\)/);assert.match(model,/deriveNextAction\(/);assert.doesNotMatch(model,/priorityWeight|priorityScore/);assert.equal(RECENTLY_LOST_DAYS,14);});
