"use client";
import { useState } from "react";
import styles from "./workspace.module.css";

type Json=Record<string,unknown>;
const money=(v:unknown)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)||0);
const when=(v:unknown)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(String(v))):"—";
export default function CaseWorkspace({initialData}:{initialData:Json}){
  const [data,setData]=useState(initialData),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const id=(data.case as Json).id as string;
  async function act(payload:Json){setBusy(true);setMessage("");const response=await fetch(`/api/cases/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok){setMessage(result.error??"Falha operacional.");setBusy(false);return}const fresh=await fetch(`/api/cases/${id}`,{cache:"no-store"});setData(await fresh.json());setMessage(result.title??"Operação concluída.");setBusy(false)}
  const vehicle=data.vehicle as Json,summary=data.summary as Json,matches=data.matches as Json[],eligibleMatches=matches.filter(match=>match.hardConstraintPass!==false),work=data.workOrders as Json[],publications=data.publications as Json[],proposals=data.proposals as Json[],contracts=data.contracts as Json[],payments=data.payments as Json[],deliveries=data.deliveries as Json[],followups=data.followups as Json[],timeline=data.timeline as Json[];
  const promptText=(label:string,initial="")=>window.prompt(label,initial)?.trim()??"";const promptMoney=(label:string,initial=0)=>Number(window.prompt(label,String(initial))??NaN);
  return <div className={styles.workspace}>
    <section className={styles.metrics}><div><span>Status</span><b>{String((data.case as Json).status).replaceAll("_"," ")}</b></div><div><span>Custos</span><b>{money(summary.totalCosts)}</b></div><div><span>Fotos aprovadas</span><b>{String(summary.approvedPhotos)}</b></div><div><span>Pagamentos liquidados</span><b>{money(summary.settledPayments)}</b></div></section>
    {message&&<div className={styles.message}>{message}</div>}
    <div className={styles.columns}><main>
      <Panel title="Ordens de serviço" action={<button disabled={busy} onClick={()=>{const workType=promptText("Tipo","maintenance"),description=promptText("Descrição"),estimatedCost=promptMoney("Custo estimado");if(workType&&Number.isFinite(estimatedCost))void act({type:"work_order.create",workType,description,estimatedCost})}}>Nova ordem</button>}>
        {work.map(x=><Row key={String(x.id)} title={`${x.workType} · ${x.status}`} meta={`${money(x.actualCost||x.estimatedCost)} · ${x.description}`} actions={x.status==="open"||x.status==="in_progress"?<><button disabled={busy} onClick={()=>void act({type:"work_order.transition",id:x.id,status:"in_progress"})}>Iniciar</button><button disabled={busy} onClick={()=>{const actualCost=promptMoney("Custo real",Number(x.estimatedCost));if(Number.isFinite(actualCost))void act({type:"work_order.transition",id:x.id,status:"completed",actualCost})}}>Concluir</button></>:null}/>)}</Panel>
      <Panel title="Publicações" action={<button disabled={busy} onClick={()=>{const channel=promptText("Canal","autoponte"),askingPrice=promptMoney("Preço",Number(vehicle.askingPrice));if(channel&&Number.isFinite(askingPrice))void act({type:"publication.create",channel,askingPrice})}}>Nova publicação</button>}>
        {publications.map(x=><Row key={String(x.id)} title={`${x.channel} · ${x.status}`} meta={money(x.askingPrice)} actions={<>{x.status!=="published"&&x.status!=="ended"&&<button disabled={busy} onClick={()=>void act({type:"publication.transition",id:x.id,status:"published"})}>Publicar</button>}{x.status==="published"&&<button disabled={busy} onClick={()=>void act({type:"publication.transition",id:x.id,status:"paused"})}>Pausar</button>}{x.status!=="ended"&&<button disabled={busy} onClick={()=>void act({type:"publication.transition",id:x.id,status:"ended"})}>Encerrar</button>}</>}/>)}</Panel>
      <Panel title="Propostas" action={<button disabled={busy||!eligibleMatches.length} onClick={()=>{const price=promptMoney("Valor do veículo",Number(vehicle.askingPrice)),tradeInCredit=promptMoney("Crédito da troca",0),downPayment=promptMoney("Entrada",0),fees=promptMoney("Taxas",0),financedAmount=price+fees-tradeInCredit-downPayment;if([price,tradeInCredit,downPayment,fees,financedAmount].every(Number.isFinite))void act({type:"proposal.create",matchId:eligibleMatches[0].id,vehiclePrice:price,tradeInCredit,downPayment,financedAmount,installments:financedAmount?48:0,installmentAmount:financedAmount?Math.round(financedAmount/48):0,fees})}}>Nova proposta</button>}>
        {proposals.map(x=><Row key={String(x.id)} title={`#${x.sequence} · ${x.status}`} meta={`${money(x.totalAmount)} · Match ${String(x.matchId).slice(-8)}`} actions={<>{x.status==="draft"&&<button disabled={busy} onClick={()=>void act({type:"proposal.transition",id:x.id,status:"sent"})}>Enviar</button>}{x.status==="sent"&&<><button disabled={busy} onClick={()=>void act({type:"proposal.transition",id:x.id,status:"accepted"})}>Aceitar</button><button disabled={busy} onClick={()=>{const reason=promptText("Motivo da rejeição");if(reason)void act({type:"proposal.transition",id:x.id,status:"rejected",reason})}}>Rejeitar</button></>}</>}/>)}</Panel>
      <Panel title="Contratos e pagamentos">
        {contracts.map(x=><Row key={String(x.id)} title={`Contrato ${x.contractNumber||x.contractType} · ${x.status}`} meta={when(x.signedAt)} actions={x.status==="draft"?<button disabled={busy} onClick={()=>void act({type:"contract.transition",id:x.id,status:"signed"})}>Assinar</button>:null}/>)}
        {proposals.filter(x=>x.status==="accepted"&&!contracts.some(c=>c.proposalId===x.id)).map(x=><button className={styles.wide} disabled={busy} key={String(x.id)} onClick={()=>void act({type:"contract.create",proposalId:x.id,contractType:"purchase_and_sale",contractNumber:promptText("Número do contrato")})}>Criar contrato da proposta #{String(x.sequence)}</button>)}
        {payments.map(x=><Row key={String(x.id)} title={`${x.paymentType} · ${x.status}`} meta={`${money(x.amount)} · ${x.provider||"Sem provedor"}`} actions={x.status==="pending"?<button disabled={busy} onClick={()=>void act({type:"payment.transition",id:x.id,status:"settled"})}>Liquidar</button>:null}/>)}
        {proposals.filter(x=>x.status==="accepted").map(x=><button className={styles.wide} disabled={busy} key={`pay-${String(x.id)}`} onClick={()=>{const amount=promptMoney("Valor do pagamento",Number(x.totalAmount));if(Number.isFinite(amount))void act({type:"payment.create",proposalId:x.id,paymentType:promptText("Tipo","financing"),provider:promptText("Provedor"),amount})}}>Registrar pagamento da proposta #{String(x.sequence)}</button>)}
      </Panel>
      <Panel title="Entrega e pós-venda">
        {deliveries.map(x=><Row key={String(x.id)} title={`Entrega · ${x.status}`} meta={when(x.deliveredAt||x.scheduledAt)} actions={x.status==="scheduled"?<button disabled={busy} onClick={()=>void act({type:"delivery.complete",checklist:{documents:true,keys:true,inspection:true},notes:"Checklist confirmado na operação"})}>Concluir entrega</button>:null}/>)}
        {!deliveries.length&&<button className={styles.wide} disabled={busy} onClick={()=>{const scheduledAt=promptText("Data/hora ISO",new Date(Date.now()+86400000).toISOString());if(scheduledAt)void act({type:"delivery.schedule",scheduledAt})}}>Agendar entrega</button>}
        {followups.map(x=><Row key={String(x.id)} title={`Pós-venda · ${x.status}`} meta={when(x.dueAt)} actions={x.status==="scheduled"?<button disabled={busy} onClick={()=>{const outcome=promptText("Resultado");if(outcome)void act({type:"post_sale.complete",id:x.id,outcome})}}>Concluir</button>:null}/>)}
        {deliveries.some(x=>x.status==="delivered")&&<button className={styles.wide} disabled={busy} onClick={()=>{const dueAt=promptText("Data/hora ISO",new Date(Date.now()+7*86400000).toISOString());if(dueAt)void act({type:"post_sale.schedule",dueAt})}}>Agendar pós-venda</button>}
      </Panel>
      <Panel title="Match Engine">{matches.map(x=><Row key={String(x.id)} title={`${x.vehicleLabel} · score ${x.score}`} meta={`${(x.reasons as string[]).join(" · ")} · resultado: ${x.outcome||x.status}`}/>)}</Panel>
    </main><aside><Panel title="Linha do tempo unificada">{timeline.map(x=><div className={styles.event} key={String(x.id)}><i/><div><b>{String(x.eventType).replaceAll("_"," ")}</b><p>{String(x.description||x.status)}</p><small>{when(x.occurredAt)}</small></div></div>)}</Panel></aside></div>
  </div>;
}
function Panel({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className={styles.panel}><header><h2>{title}</h2>{action}</header><div className={styles.body}>{children}</div></section>}
function Row({title,meta,actions}:{title:string;meta:string;actions?:React.ReactNode}){return <div className={styles.row}><div><b>{title}</b><small>{meta}</small></div>{actions&&<div className={styles.actions}>{actions}</div>}</div>}
