"use client";

import { FormEvent, PointerEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import type { PublicMarketplaceVehicle } from "../../lib/marketplace/public-vehicles";
import home from "./home-vision.module.css";
import work from "../match-workspace/workspace.module.css";

type Match={vehicle:PublicMarketplaceVehicle;score:number;reasons:string[]};type MatchResponse={recommendations?:Match[];error?:string};type Stage="home"|"matches"|"vehicle";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});const number=new Intl.NumberFormat("pt-BR");
function vehicleImage(t:string){t=t.toLowerCase();if(t.includes("sedan"))return"/vehicle-sedan.png";if(t.includes("hatch"))return"/vehicle-hatch.png";return"/vehicle-suv.png"}
export default function AutoPonteExperience({initialVehicles}:{initialVehicles:PublicMarketplaceVehicle[]}){const[stage,setStage]=useState<Stage>("home");const[query,setQuery]=useState("");const[matches,setMatches]=useState<Match[]>([]);const[selected,setSelected]=useState<number|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[homeWidth,setHomeWidth]=useState(36);const[matchWidth,setMatchWidth]=useState(34);const[dragging,setDragging]=useState<"home"|"match"|null>(null);const shellRef=useRef<HTMLDivElement|null>(null);const active=selected===null?null:matches[selected];const stores=Array.from(new Map(initialVehicles.map(v=>[v.partner.id,v.partner])).values()).slice(0,5);
useEffect(()=>{window.history.replaceState({apStage:"home"},"");const pop=(e:PopStateEvent)=>{const s=e.state as{apStage?:Stage;selected?:number}|null;if(s?.apStage==="vehicle"&&typeof s.selected==="number"){setStage("vehicle");setSelected(s.selected)}else if(s?.apStage==="matches"){setStage("matches");setSelected(null)}else{setStage("home");setSelected(null)}};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[]);
function push(s:Stage,i?:number){window.history.pushState({apStage:s,selected:i},"")}function goHome(){setStage("home");setSelected(null);push("home")}
async function runSearch(search:string,openId?:string){const clean=search.trim();if(!clean)return;setLoading(true);setError("");setSelected(null);setStage("matches");push("matches");try{const r=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preferredModels:clean,budgetMax:0,maxMatches:60})});const p=await r.json() as MatchResponse;if(!r.ok)throw new Error(p.error||"Não foi possível calcular os Matches.");const next=p.recommendations||[];setMatches(next);if(openId){const i=next.findIndex(x=>x.vehicle.id===openId);if(i>=0){setSelected(i);setStage("vehicle");push("vehicle",i)}}}catch(c){setMatches([]);setError(c instanceof Error?c.message:"Não foi possível calcular os Matches.")}finally{setLoading(false)}}
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const v=String(new FormData(e.currentTarget).get("q")||query);setQuery(v);void runSearch(v)}function openInventory(v:PublicMarketplaceVehicle){const q=`${v.brand} ${v.model}`;setQuery(q);void runSearch(q,v.id)}function choose(i:number){setSelected(i);setStage("vehicle");push("vehicle",i)}
function moveDivider(clientX:number,kind:"home"|"match"){const b=shellRef.current?.getBoundingClientRect();if(!b)return;const pct=((clientX-b.left)/b.width)*100;if(kind==="home"){const max=stage==="vehicle"?45:70;setHomeWidth(Math.max(16,Math.min(max,pct)))}else{const start=homeWidth;const end=Math.max(start+18,Math.min(84,pct));setMatchWidth(end-start)}}function startDrag(e:PointerEvent<HTMLDivElement>,kind:"home"|"match"){if(window.matchMedia("(max-width: 760px)").matches)return;e.currentTarget.setPointerCapture(e.pointerId);setDragging(kind);moveDivider(e.clientX,kind)}function drag(e:PointerEvent<HTMLDivElement>,kind:"home"|"match"){if(dragging===kind)moveDivider(e.clientX,kind)}function stop(e:PointerEvent<HTMLDivElement>){if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setDragging(null)}
const cols=stage==="home"?"100%":stage==="matches"?`${homeWidth}% 8px minmax(0,1fr)`: `${homeWidth}% 8px ${matchWidth}% 8px minmax(0,1fr)`;
return <main className={home.page}><header className={home.header}><button className={home.brandButton} onClick={goHome}><span>AP</span><b>AutoPonte</b></button><nav className={home.nav}><button onClick={goHome}>Comprar</button><button>Vender</button><button>Trocar</button><button>Como funciona</button><button>Lojas</button></nav><div className={home.headerActions}><button className={home.heart}>♡</button><Link className={home.login} href="/crm">Entrar</Link></div></header><div ref={shellRef} className={`${home.progressiveShell} ${home[`stage_${stage}`]}`} style={{gridTemplateColumns:cols}}>
<section className={home.homePane}><div className={home.paneScroll}><section className={home.hero}><div className={home.heroBackdrop}/><div className={home.heroContent}><p className={home.eyebrow}>AUTOPONTE MATCH</p><h1>Encontre o carro certo. A AutoPonte faz o Match para você.</h1><p className={home.heroText}>Conte o que procura. Nossa inteligência cruza sua intenção com o estoque real.</p><div className={home.entryGrid}><form className={home.searchPanel} onSubmit={submit}><label>Já sabe o que procura?</label><p>Busque por modelo, categoria ou descreva o carro ideal.</p><div className={home.searchRow}><input name="q" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: Jeep Compass automático" required/><button>Buscar</button></div></form><div className={home.aiPanel}><div><span className={home.aiMark}>✦</span><div><strong>Ainda não sabe por onde começar?</strong><p>A IA ajuda a descobrir o carro certo.</p></div></div><Link href="/atendimento">Começar Busca Inteligente</Link></div></div></div></section><section className={home.how}><div className={home.sectionHeading}><p className={home.eyebrow}>COMO FUNCIONA</p><h2>Em 3 passos.</h2></div><div className={home.steps}>{[["1","Conte o que você precisa"],["2","A IA faz o Match"],["3","Receba os melhores Matches"]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3></article>)}</div></section><section className={home.inventory}><div className={home.sectionHeadingRow}><div><p className={home.eyebrow}>RECÉM-CHEGADOS</p><h2>Novidades no estoque.</h2></div></div><div className={home.vehicleGrid}>{initialVehicles.slice(0,10).map(v=><article className={home.vehicleCard} key={v.id} role="button" tabIndex={0} onClick={()=>openInventory(v)}><div className={home.vehicleImageWrap}><img src={vehicleImage(v.bodyType)} alt={`${v.brand} ${v.model}`}/></div><div className={home.vehicleBody}><p className={home.verified}>✓ Loja verificada</p><h3>{v.brand} {v.model}</h3><p>{v.modelYear} · {number.format(v.mileage)} km</p><strong>{money.format(v.price)}</strong></div></article>)}</div></section><section className={home.storeSection}><div className={home.sectionHeadingRow}><div><p className={home.eyebrow}>LOJAS VERIFICADAS</p><h2>Compre com mais confiança.</h2></div></div><div className={home.storeGrid}>{stores.map(s=><article className={home.storeCard} key={s.id}><div className={home.storeLogo}>AP</div><div><p>✓ VERIFICADA</p><h3>{s.name}</h3><span>{s.city}</span></div></article>)}</div></section></div></section>
{stage!=="home"&&<><div className={home.splitDivider} role="separator" onPointerDown={e=>startDrag(e,"home")} onPointerMove={e=>drag(e,"home")} onPointerUp={stop} onPointerCancel={stop}><span>⋮</span></div><section className={home.matchPane}><div className={home.matchTop}><p>RESULTADO DE BUSCA</p><h2>{loading?"Calculando…":`${matches.length} Matches`}</h2><form onSubmit={submit}><input name="q" value={query} onChange={e=>setQuery(e.target.value)}/><button>Refinar</button></form></div><div className={home.matchList}>{matches.map((m,i)=><button key={m.vehicle.id} className={`${home.matchCard} ${i===selected?home.matchActive:""}`} onClick={()=>choose(i)}><img src={vehicleImage(m.vehicle.bodyType)} alt=""/><div><span>{m.score}% match</span><strong>{m.vehicle.brand} {m.vehicle.model}</strong><p>{m.vehicle.modelYear} · {number.format(m.vehicle.mileage)} km</p><b>{money.format(m.vehicle.price)}</b></div></button>)}</div>{error&&<p className={home.paneError}>{error}</p>}</section></>}
{stage==="vehicle"&&active&&<><div className={home.splitDivider} role="separator" onPointerDown={e=>startDrag(e,"match")} onPointerMove={e=>drag(e,"match")} onPointerUp={stop} onPointerCancel={stop}><span>⋮</span></div><section className={home.detailPane}><div className={home.detailScroll}><div className={home.detailTop}><span>{active.score}% MATCH</span><button onClick={()=>window.history.back()}>Fechar</button></div><div className={home.detailHero}><img src={vehicleImage(active.vehicle.bodyType)} alt={`${active.vehicle.brand} ${active.vehicle.model}`}/></div><div className={home.detailInfo}><p>{active.vehicle.partner.name} · VERIFICADA</p><h2>{active.vehicle.brand} {active.vehicle.model}</h2><strong>{money.format(active.vehicle.price)}</strong><span>{active.vehicle.modelYear} · {number.format(active.vehicle.mileage)} km · {active.vehicle.city}</span><div className={home.detailActions}><button>Tenho interesse</button><button>Simular financiamento</button></div><section><p>POR QUE DEU MATCH?</p><ul>{active.reasons.slice(0,5).map(r=><li key={r}>✓ {r}</li>)}</ul></section><aside className={home.assistant}><b>✦ AutoPonte Assistant</b><p>Posso explicar o Match, comparar opções e ajudar nos próximos passos.</p><button>Conversar com o Assistant</button></aside></div></div></section></>}
</div></main>}
