import Link from "next/link";
import { listPublicMarketplaceVehicles } from "../../lib/marketplace/public-vehicles";
import styles from "./home-vision.module.css";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
function vehicleImage(bodyType:string){const type=bodyType.toLowerCase();if(type.includes("sedan"))return "/vehicle-sedan.png";if(type.includes("hatch"))return "/vehicle-hatch.png";return "/vehicle-suv.png"}
export default async function HomeVisionPreview(){const vehicles=await listPublicMarketplaceVehicles(8);return <main className={styles.page}><header className={styles.header}><Link className={styles.brand} href="/home-vision" aria-label="AutoPonte início"><span>Auto</span>Ponte</Link><nav className={styles.nav}><a href="#comprar">Comprar</a><a href="#como-funciona">Como funciona</a><a href="#lojas">Lojas verificadas</a></nav><div className={styles.headerActions}><Link className={styles.ghostAction} href="/crm">Área da loja</Link><Link className={styles.primaryAction} href="/atendimento">Busca inteligente</Link></div></header>
<section className={styles.hero}><div className={styles.heroBackdrop}/><div className={styles.heroContent}><p className={styles.eyebrow}>AutoPonte Match</p><h1>Encontrar um carro é fácil. Encontrar o seu é AutoPonte.</h1><p className={styles.heroText}>Encontramos o seu carro com inteligência, conectando suas preferências aos melhores matches disponíveis.</p><form className={styles.searchPanel} action="/match-workspace" method="get"><label htmlFor="smart-search">Já sabe mais ou menos o que procura?</label><div className={styles.searchRow}><input id="smart-search" name="q" placeholder="Ex.: SUV automático até R$ 150 mil em São Paulo" required/><button type="submit">Encontrar matches</button></div><div className={styles.searchAssist}><span>Ainda não sabe exatamente?</span><Link href="/atendimento">Experimente a Busca Inteligente →</Link></div></form></div><div className={styles.heroMedia}><div className={styles.mediaBadge}><strong>Seu próximo carro começa pelo Match</strong><span>Busca, comparação e decisão no mesmo ambiente</span></div></div></section>
<section className={styles.how} id="como-funciona"><div className={styles.sectionHeading}><p className={styles.eyebrow}>Como funciona</p><h2>Você conta o que precisa. A AutoPonte faz o resto.</h2></div><div className={styles.steps}><article><span>01</span><h3>Conte o que procura</h3><p>Orçamento, rotina, preferências e o que realmente importa para você.</p></article><article><span>02</span><h3>A IA faz o Match</h3><p>Cruzamos intenção, estoque e contexto para reduzir centenas de opções.</p></article><article><span>03</span><h3>Explore os melhores</h3><p>Compare os Matches e abra cada veículo sem perder sua lista.</p></article></div></section>
<section className={styles.inventory} id="comprar"><div className={styles.sectionHeadingRow}><div><p className={styles.eyebrow}>Recém-chegados</p><h2>Veículos reais do marketplace</h2></div><Link href="/match-workspace">Encontrar meu Match →</Link></div>{vehicles.length?<div className={styles.vehicleGrid}>{vehicles.map((vehicle,index)=><article className={styles.vehicleCard} key={vehicle.id}><div className={styles.vehicleImageWrap}><img src={vehicleImage(vehicle.bodyType)} alt={`${vehicle.brand} ${vehicle.model}`}/><span className={styles.matchChip}>{Math.max(82,96-index*2)}% Match</span></div><div className={styles.vehicleBody}><p className={styles.verified}>✓ Loja verificada</p><h3>{vehicle.brand} {vehicle.model}</h3><p>{vehicle.modelYear} · {vehicle.mileage.toLocaleString("pt-BR")} km · {vehicle.transmission||"Câmbio não informado"}</p><strong>{money.format(vehicle.price)}</strong><div className={styles.vehicleFooter}><span>{vehicle.city}{vehicle.state?`, ${vehicle.state}`:""}</span><span>{vehicle.partner.name}</span></div></div></article>)}</div>:<div className={styles.emptyState}><strong>O marketplace está pronto para receber o estoque publicado.</strong><span>Assim que houver veículos disponíveis, eles aparecem aqui automaticamente.</span></div>}</section>
<section className={styles.smartSection}><div><p className={styles.eyebrow}>Busca Inteligente</p><h2>Não procure entre milhares. Comece pelos seus melhores Matches.</h2><p>A AutoPonte entende seu contexto e organiza as opções que mais fazem sentido para você.</p></div><Link className={styles.primaryAction} href="/atendimento">Começar Busca Inteligente</Link></section><section className={styles.storeSection} id="lojas"><p className={styles.eyebrow}>Confiança</p><h2>Lojas verificadas, em um só ecossistema.</h2><p>O estoque público respeita somente parceiros ativos e veículos disponíveis.</p></section></main>}
