export const catalogVehicles = [
  {
    id: 1,
    name: "SUV Urban 1.5 Turbo",
    year: "2023/2024",
    modelYear: 2024,
    km: "31.800 km",
    mileage: 31800,
    price: 119900,
    city: "São Bernardo do Campo",
    type: "SUV",
    transmission: "Automático",
    fuel: "Flex",
    useCases: ["Família", "Viagens"],
    image: "/vehicle-suv.png",
    badge: "Estoque verificado",
  },
  {
    id: 2,
    name: "Sedan Executive 2.0",
    year: "2022/2023",
    modelYear: 2023,
    km: "42.100 km",
    mileage: 42100,
    price: 104900,
    city: "São Bernardo do Campo",
    type: "Sedan",
    transmission: "Automático",
    fuel: "Flex",
    useCases: ["Família", "Trabalho", "Viagens"],
    image: "/vehicle-sedan.png",
    badge: "Boa oportunidade",
  },
  {
    id: 3,
    name: "Hatch Connect 1.0",
    year: "2024/2025",
    modelYear: 2025,
    km: "18.400 km",
    mileage: 18400,
    price: 82900,
    city: "São Bernardo do Campo",
    type: "Hatch",
    transmission: "Automático",
    fuel: "Flex",
    useCases: ["Cidade", "Trabalho", "Aplicativo"],
    image: "/vehicle-hatch.png",
    badge: "Baixa quilometragem",
  },
] as const;

export type CatalogVehicle = (typeof catalogVehicles)[number];
