import { integer, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const vehicles = pgTable("vehicles", {
  id: text("id").primaryKey(),
  inventoryScope: text("inventory_scope").notNull().default("autoponte"),
  partnerId: text("partner_id").notNull().default(""),
  sourceType: text("source_type").notNull().default("partner_inventory"),
  status: text("status").notNull().default("available"),
  plate: text("plate").notNull().default(""),
  chassis: text("chassis").notNull().default(""),
  stockCode: text("stock_code").notNull().default(""),
  brandCode: text("brand_code").notNull(),
  modelCode: text("model_code").notNull(),
  yearCode: text("year_code").notNull(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  modelYear: integer("model_year").notNull(),
  fuel: text("fuel").notNull().default(""),
  fipeCode: text("fipe_code").notNull(),
  fipeReferenceMonth: text("fipe_reference_month").notNull(),
  fipeValue: integer("fipe_value").notNull(),
  mileage: integer("mileage").notNull().default(0),
  color: text("color").notNull().default(""),
  transmission: text("transmission").notNull().default(""),
  bodyType: text("body_type").notNull().default(""),
  doors: integer("doors").notNull().default(0),
  engine: text("engine").notNull().default(""),
  power: text("power").notNull().default(""),
  renavam: text("renavam").notNull().default(""),
  registrationState: text("registration_state").notNull().default(""),
  documentStatus: text("document_status").notNull().default("regular"),
  vehicleCondition: text("vehicle_condition").notNull().default("good"),
  inspectionStatus: text("inspection_status").notNull().default("pending"),
  acquisitionDate: text("acquisition_date").notNull().default(""),
  listingDate: text("listing_date").notNull().default(""),
  optionalItems: text("optional_items").notNull().default(""),
  city: text("city").notNull().default(""),
  ownerName: text("owner_name").notNull().default(""),
  askingPrice: integer("asking_price").notNull().default(0),
  acquisitionCost: integer("acquisition_cost").notNull().default(0),
  additionalCosts: integer("additional_costs").notNull().default(0),
  notes: text("notes").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
