export const VEHICLE_FEATURE_CATEGORIES = [
  "safety",
  "comfort",
  "technology",
  "exterior",
  "interior",
  "performance",
] as const;

export type VehicleFeatureCategory = typeof VEHICLE_FEATURE_CATEGORIES[number];

export const VEHICLE_FEATURE_CATALOG = [
  ["abs", "safety", "ABS"],
  ["stability_control", "safety", "Controle de estabilidade"],
  ["traction_control", "safety", "Controle de tração"],
  ["front_airbags", "safety", "Airbags frontais"],
  ["side_airbags", "safety", "Airbags laterais"],
  ["curtain_airbags", "safety", "Airbags de cortina"],
  ["blind_spot_monitor", "safety", "Alerta de ponto cego"],
  ["aeb", "safety", "Frenagem autônoma de emergência"],
  ["forward_collision_warning", "safety", "Alerta de colisão frontal"],
  ["lane_departure_warning", "safety", "Alerta de saída de faixa"],
  ["lane_keep_assist", "safety", "Assistente de permanência em faixa"],
  ["adaptive_cruise_control", "safety", "Piloto automático adaptativo"],
  ["rear_camera", "safety", "Câmera de ré"],
  ["camera_360", "safety", "Câmera 360°"],
  ["front_parking_sensor", "safety", "Sensor de estacionamento dianteiro"],
  ["rear_parking_sensor", "safety", "Sensor de estacionamento traseiro"],
  ["isofix", "safety", "ISOFIX"],
  ["air_conditioning", "comfort", "Ar-condicionado"],
  ["automatic_climate", "comfort", "Climatização automática"],
  ["dual_zone_climate", "comfort", "Climatização dual-zone"],
  ["electric_front_seats", "comfort", "Bancos dianteiros elétricos"],
  ["seat_memory", "comfort", "Memória dos bancos"],
  ["heated_seats", "comfort", "Bancos aquecidos"],
  ["ventilated_seats", "comfort", "Bancos ventilados"],
  ["sunroof", "comfort", "Teto solar"],
  ["panoramic_roof", "comfort", "Teto panorâmico"],
  ["push_button_start", "comfort", "Partida por botão"],
  ["keyless_entry", "comfort", "Acesso keyless"],
  ["power_tailgate", "comfort", "Porta-malas elétrico"],
  ["apple_carplay", "technology", "Apple CarPlay"],
  ["android_auto", "technology", "Android Auto"],
  ["wireless_carplay", "technology", "CarPlay sem fio"],
  ["wireless_android_auto", "technology", "Android Auto sem fio"],
  ["navigation", "technology", "Navegação"],
  ["digital_cluster", "technology", "Painel digital"],
  ["head_up_display", "technology", "Head-up display"],
  ["wireless_charger", "technology", "Carregador sem fio"],
  ["bluetooth", "technology", "Bluetooth"],
  ["usb_c", "technology", "USB-C"],
  ["led_headlights", "exterior", "Faróis LED"],
  ["matrix_led", "exterior", "Faróis Matrix LED"],
  ["drl", "exterior", "Luzes diurnas"],
  ["alloy_wheels", "exterior", "Rodas de liga leve"],
  ["roof_rails", "exterior", "Barras de teto"],
  ["leather_seats", "interior", "Bancos em couro"],
  ["alcantara", "interior", "Acabamento Alcantara"],
  ["ambient_lighting", "interior", "Iluminação ambiente"],
  ["sport_mode", "performance", "Modo Sport"],
  ["paddle_shift", "performance", "Paddle shift"],
  ["adaptive_suspension", "performance", "Suspensão adaptativa"],
  ["awd_4x4", "performance", "Tração integral / 4x4"],
] as const;

export type VehicleFeatureCode = typeof VEHICLE_FEATURE_CATALOG[number][0];
