import { sql } from "drizzle-orm";
import { boolean, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const tradeIns = pgTable("trade_ins", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  whatsapp: text("whatsapp").notNull(),
  email: text("email").notNull(),
  city: text("city").notNull(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  version: text("version").notNull(),
  year: text("year").notNull(),
  mileage: integer("mileage").notNull(),
  condition: text("condition").notNull(),
  desiredVehicle: text("desired_vehicle").notNull().default(""),
  referencePrice: integer("reference_price").notNull(),
  fipeCode: text("fipe_code").notNull().default(""),
  fipeMonth: text("fipe_month").notNull().default(""),
  estimatedMin: integer("estimated_min").notNull(),
  estimatedMax: integer("estimated_max").notNull(),
  photoKeys: text("photo_keys").notNull(),
  status: text("status").notNull().default("pre_evaluated"),
  leadCategory: text("lead_category").notNull().default("new"),
  nextFollowUp: text("next_follow_up").notNull().default(""),
  lastContactAt: text("last_contact_at").notNull().default(""),
  notes: text("notes").notNull().default(""),
  consentAt: text("consent_at").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const consignments = pgTable("consignments", {
  id: text("id").primaryKey(),
  accessTokenHash: text("access_token_hash").notNull(),
  ownerName: text("owner_name").notNull(),
  whatsapp: text("whatsapp").notNull(),
  email: text("email").notNull(),
  city: text("city").notNull(),
  vehicleName: text("vehicle_name").notNull(),
  year: text("year").notNull(),
  mileage: integer("mileage").notNull(),
  plate: text("plate").notNull().default(""),
  askingPrice: integer("asking_price").notNull(),
  minimumPrice: integer("minimum_price").notNull(),
  photoKeys: text("photo_keys").notNull().default("[]"),
  status: text("status").notNull().default("intake_received"),
  consentAt: text("consent_at").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const buyerProfiles = pgTable("buyer_profiles", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  whatsapp: text("whatsapp").notNull(),
  email: text("email").notNull(),
  city: text("city").notNull(),
  budgetMax: integer("budget_max").notNull(),
  downPayment: integer("down_payment").notNull().default(0),
  maxMonthlyPayment: integer("max_monthly_payment").notNull().default(0),
  vehicleTypes: text("vehicle_types").notNull().default("[]"),
  preferredModels: text("preferred_models").notNull().default(""),
  minYear: integer("min_year").notNull().default(0),
  maxMileage: integer("max_mileage").notNull().default(999999),
  transmission: text("transmission").notNull().default("Indiferente"),
  fuel: text("fuel").notNull().default("Indiferente"),
  useCase: text("use_case").notNull().default(""),
  purchaseTimeline: text("purchase_timeline").notNull().default("Sem urgência"),
  alertsConsent: boolean("alerts_consent").notNull().default(false),
  consentAt: text("consent_at").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const vehicleMatches = pgTable("vehicle_matches", {
  id: text("id").primaryKey(),
  buyerProfileId: text("buyer_profile_id").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: text("source_id").notNull(),
  vehicleLabel: text("vehicle_label").notNull(),
  vehiclePrice: integer("vehicle_price").notNull().default(0),
  score: integer("score").notNull(),
  reasons: text("reasons").notNull().default("[]"),
  messageDraft: text("message_draft").notNull().default(""),
  status: text("status").notNull().default("review_pending"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  reviewedAt: text("reviewed_at").notNull().default(""),
}, (table) => [
  uniqueIndex("vehicle_matches_source_buyer_unique").on(table.sourceType, table.sourceId, table.buyerProfileId),
]);
