"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

type Result = { existingMatches: number; recommendations: Array<{ score: number; reasons: string[]; vehicle: { id: number; name: string; year: string; km: string; price: number; city: string; image: string } }> };
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });

export default function AtendimentoPage() {
  const [types, setTypes] = useState<string[]>([]);
  const [purchaseMode, setPurchaseMode] = useState<"direct" | "trade" | null>(null);
  const [status, setStatus] = useState<"idle" | "sending" | "done" | "error">("idle");
  const [error, setError] = useState("");
  const [result, setResult] = useState<Result | null>(null);
  function toggleType(type: string) { setTypes((current) => current.includes(type) ? current.filter((item) => item !== type) : [...current, type]); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending"); setError(""); setResult(null);
    const form = new FormData(event.currentTarget);
    const payload = Object.fromEntries(form.entries()) as Record<string, FormDataEntryValue>;
    try {
      const response = await fetch("/api/buyer-profiles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({
        ...payload, vehicleTypes: types, budgetMax: Number(payload.budgetMax), downPayment: Number(payload.downPayment),
        maxMonthlyPayment: Number(payload.maxMonthlyPayment), minYear: Number(payload.minYear), maxMileage: Number(payload.maxMileage),
        alertsConsent: form.get("alertsConsent") === "yes", consent: form.get("consent") === "yes",
      }) });
      const data = await response.json() as Result & { error?: string };
      if (!response.ok) throw new Error(data.error || "Não foi possível concluir a busca.");
      setResult(data); setStatus("done");
    } catch (issue) { setError(issue instanceof Error ? issue.message : "Não foi possível concluir a busca."); setStatus("error"); }
  }
  return <main className="match-assistant-page">
    <header className="site-header"><Link className="brand" href="/"><span>AutoPonte</span> Veículos</Link><Link className="request-back" href="/">← Voltar ao portal</Link></header>
    <section className="assistant-layout">
      <aside className="assistant-intro"><p className="eyebrow">AutoPonte Match</p><h1>Conte o que precisa. A gente encontra os melhores caminhos.</h1><p>Suas respostas viram um perfil de compra. O sistema compara orçamento, categoria, ano, quilometragem e uso para explicar cada recomendação.</p><ol><li><span>1</span>Preferências e orçamento</li><li><span>2</span>Recomendações explicadas</li><li><span>3</span>Novos Matches, com sua autorização</li></ol></aside>
      <form className="assistant-form" onSubmit={submit}>
        <div className="assistant-bubble"><b>Olá! Sou o assistente AutoPonte.</b><span>Vou fazer algumas perguntas rápidas para encontrar carros compatíveis com você.</span></div>
        <fieldset className="purchase-path"><legend>Como você pretende comprar?</legend><div className="purchase-path-grid"><button type="button" className={purchaseMode === "direct" ? "selected" : ""} onClick={() => setPurchaseMode("direct")}><span>01</span><div><b>Comprar sem troca</b><small>Quero escolher e simular um veículo.</small></div></button><button type="button" className={purchaseMode === "trade" ? "selected" : ""} onClick={() => setPurchaseMode("trade")}><span>02</span><div><b>Tenho um carro na troca</b><small>Quero usar meu veículo como entrada.</small></div></button></div><input className="sr-only" name="purchaseMode" value={purchaseMode ?? ""} readOnly required aria-label="Modalidade de compra" />{!purchaseMode && <p className="path-help">Escolha uma opção para personalizarmos o atendimento.</p>}{purchaseMode === "direct" && <div className="path-confirmation"><strong>Compra direta selecionada</strong><span>Vamos recomendar veículos e preparar uma simulação orientativa.</span></div>}{purchaseMode === "trade" && <div className="trade-quick-intake"><div><strong>Cadastro rápido do veículo usado</strong><span>Agora bastam informações básicas. As fotos, FIPE e avaliação detalhada serão solicitadas depois que você escolher o veículo de interesse.</span></div><div className="form-grid two"><label>Marca e modelo<input name="tradeVehicle" required placeholder="Ex.: Honda Fit" /></label><label>Ano<input name="tradeYear" required type="number" min="1990" max="2030" placeholder="Ex.: 2018" /></label><label>Quilometragem aproximada<input name="tradeMileage" required type="number" min="0" max="900000" placeholder="Ex.: 65000" /></label><label>Situação financeira<select name="tradeFinance"><option>Quitado</option><option>Financiado</option><option>Possui débitos</option><option>Não sei informar</option></select></label></div><p>Após as recomendações, você poderá iniciar o AutoPonte Fotos para consultar a FIPE e enviar as imagens orientadas.</p></div>}</fieldset>
        <fieldset><legend>Que tipo de carro combina com sua rotina?</legend><div className="choice-grid">{["SUV", "Sedan", "Hatch", "Picape"].map((type) => <button type="button" className={types.includes(type) ? "selected" : ""} onClick={() => toggleType(type)} key={type}>{type}</button>)}</div><label>Modelos ou marcas que prefere (opcional)<input name="preferredModels" placeholder="Ex.: Creta, Corolla, Honda" /></label></fieldset>
        <fieldset><legend>Qual é o seu cenário financeiro?</legend><div className="form-grid two"><label>Orçamento máximo<input name="budgetMax" type="number" min="10000" required placeholder="Ex.: 100000" /></label><label>Valor de entrada<input name="downPayment" type="number" min="0" defaultValue="0" /></label><label>Parcela máxima desejada<input name="maxMonthlyPayment" type="number" min="0" defaultValue="0" /></label><label>Prazo para comprar<select name="purchaseTimeline" defaultValue="Até 30 dias"><option>Imediato</option><option>Até 30 dias</option><option>Até 90 dias</option><option>Sem urgência</option></select></label></div></fieldset>
        <fieldset><legend>Quais características são importantes?</legend><div className="form-grid two"><label>Ano mínimo<input name="minYear" type="number" min="1990" max="2030" defaultValue="2020" /></label><label>Quilometragem máxima<input name="maxMileage" type="number" min="0" defaultValue="80000" /></label><label>Câmbio<select name="transmission"><option>Indiferente</option><option>Automático</option><option>Manual</option></select></label><label>Combustível<select name="fuel"><option>Indiferente</option><option>Flex</option><option>Gasolina</option><option>Diesel</option><option>Elétrico</option><option>Híbrido</option></select></label><label>Uso principal<select name="useCase"><option>Cidade</option><option>Família</option><option>Trabalho</option><option>Aplicativo</option><option>Viagens</option></select></label><label>Cidade<input name="city" required defaultValue="São Bernardo do Campo" /></label></div></fieldset>
        <fieldset><legend>Como podemos continuar o atendimento?</legend><div className="form-grid two"><label>Nome<input name="name" required autoComplete="name" /></label><label>WhatsApp<input name="whatsapp" required type="tel" autoComplete="tel" placeholder="(11) 99999-9999" /></label><label>E-mail<input name="email" required type="email" autoComplete="email" /></label></div><label className="consent"><input name="alertsConsent" value="yes" type="checkbox" /><span>Quero receber alertas quando surgir um veículo compatível. Nenhuma mensagem será enviada sem esta autorização.</span></label><label className="consent"><input name="consent" value="yes" type="checkbox" required /><span>Autorizo o tratamento dos meus dados para recomendação, atendimento e contato relacionado à minha busca.</span></label></fieldset>
        {error && <p className="form-error" role="alert">{error}</p>}<button className="trade-submit" disabled={status === "sending"}>{status === "sending" ? "Calculando compatibilidades…" : "Encontrar carros compatíveis"}</button>
        {result && <section className="recommendation-result" aria-live="polite"><div><p className="eyebrow">Resultado personalizado</p><h2>Melhores combinações do estoque atual</h2><p className="recommendation-hint">Escolha uma oferta para ver os detalhes e simular as condições.</p></div>{result.recommendations.length ? <div className="recommendation-grid">{result.recommendations.map(({ vehicle, score, reasons }) => <article key={vehicle.id}><img src={vehicle.image} alt={vehicle.name} /><div><span className="match-score">{score}% compatível</span><h3>{vehicle.name}</h3><p>{vehicle.year} • {vehicle.km} • {vehicle.city}</p><strong>{brl.format(vehicle.price)}</strong><ul>{reasons.slice(0, 4).map((reason) => <li key={reason}>✓ {reason}</li>)}</ul><a className="offer-action" href={`/?vehicle=${vehicle.id}&match=${score}#estoque`} aria-label={`Ver oferta e simular ${vehicle.name}`}>Ver oferta e simular <span>→</span></a>{purchaseMode === "trade" && <a className="trade-photo-action" href={`/?vehicle=${vehicle.id}&match=${score}#troca`}>Avaliar meu carro para esta troca →</a>}</div></article>)}</div> : <p className="assistant-empty">Ainda não há um carro suficientemente compatível no estoque demonstrativo. Seu perfil ficou salvo para novos cruzamentos.</p>}<p className="match-followup">Perfil salvo. Encontramos {result.existingMatches} possível(is) correspondência(s) entre avaliações e consignações já recebidas; a equipe revisará cada uma antes de qualquer contato.</p></section>}
      </form>
    </section>
  </main>;
}
